version: '3'

services:

  hugo:
    image: 'dpurge/hugo'
    command: hugo server --disableFastRender -D
    ports:
      - '1313:1313'
    volumes:
      - ./site:/site

  # nginx:
  #   image: 'jdp/nginx'
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - ./site/public:/usr/share/nginx/html
