version: '3'

services:

  hugo:
    image: 'dpurge/hugo'
    # command: hugo server --baseUrl=localhost --bind="0.0.0.0" --disableFastRender --verbose
    command: hugo --watch
    volumes:
      - ./site:/site

  nginx:
    image: 'nginx'
    depends_on:
      - "hugo"
    ports:
      - '8080:80'
    volumes:
      - ./site/public:/usr/share/nginx/html
