FROM node:alpine

# Build: docker build -f Dockerfile.dev -t jdp/hugo:latest .
# Run server: docker run -p 1313:1313 -v ${PWD}:/var/hugo jdp/hugo hugo server -D

ENV HUGO_RELEASES https://github.com/gohugoio/hugo/releases
ENV HUGO_VERSION 0.80.0
ENV HUGO_BINARY hugo_${HUGO_VERSION}_Linux-64bit

# sources
RUN mkdir /var/hugo
WORKDIR /var/hugo

# pygments and bash
RUN apk update \
    && apk add py-pygments \
    && apk add bash \
    && rm -rf /var/cache/apk/*

# hugo
RUN mkdir /usr/local/hugo
ADD ${HUGO_RELEASES}/download/v${HUGO_VERSION}/${HUGO_BINARY}.tar.gz /usr/local/hugo/
RUN tar xzf /usr/local/hugo/${HUGO_BINARY}.tar.gz -C /usr/local/hugo/ \
	&& ln -s /usr/local/hugo/hugo /usr/local/bin/hugo \
	&& rm /usr/local/hugo/${HUGO_BINARY}.tar.gz

EXPOSE 1313
CMD ["hugo", "version"]
